name: Custom Trigger

on:
  workflow_dispatch:

jobs:
  manual-trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Triggered Manually
        uses: ./.github/actions/restfulObjects
